backend:
  name: github
  repo: GraniLuk/CookBook
  branch: main
  auth_type: pkce
  base_url: https://cookbook-cms-oauth.onrender.com/
  auth_endpoint: /auth
  app_id: Ov23liNlYyyS8AIONc4D
  scope: repo

site_url: https://graniluk.github.io/CookBook/
local_backend: true
publish_mode: simple
media_folder: static/images/uploaded
public_folder: /CookBook/images/uploaded
slug:
  encoding: ascii
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: recipes
    label: Przepisy
    label_singular: Przepis
    folder: content
    create: true
    slug: "{{slug}}"
    extension: md
    format: frontmatter
    nested:
      depth: 2
      summary: "{{title}}"
    fields:
      - { label: Tytuł, name: title, widget: string }
      - { label: Autor, name: author, widget: string, required: false }
      - { label: Szkic, name: draft, widget: boolean, required: false, default: false }
      - { label: Opis skrócony, name: tagline, widget: string, required: false }
      - { label: Obrazek przepisu (static/...), name: recipe_image, widget: string, required: false }
      - label: Tagi
        name: tags
        widget: select
        multiple: true
        required: false
        options:
          - { label: "", value: "" }
          - { label: "awokado", value: "awokado" }
          - { label: "batony", value: "batony" }
          - { label: "berberys", value: "berberys" }
          - { label: "bez-pieczenia", value: "bez-pieczenia" }
          - { label: "brownie", value: "brownie" }
          - { label: "czekolada", value: "czekolada" }
          - { label: "draft", value: "draft" }
          - { label: "goście", value: "goście" }
          - { label: "grill", value: "grill" }
          - { label: "impreza", value: "impreza" }
          - { label: "instant pot", value: "instant pot" }
          - { label: "jabłka", value: "jabłka" }
          - { label: "jajko", value: "jajko" }
          - { label: "jesień", value: "jesień" }
          - { label: "kinder bueno", value: "kinder bueno" }
          - { label: "klasyczne", value: "klasyczne" }
          - { label: "kurczak", value: "kurczak" }
          - { label: "kuskus", value: "kuskus" }
          - { label: "low carb", value: "low carb" }
          - { label: "lunchbox", value: "lunchbox" }
          - { label: "marokański", value: "marokański" }
          - { label: "meksykańskie", value: "meksykańskie" }
          - { label: "na-wynos", value: "na-wynos" }
          - { label: "owsianka", value: "owsianka" }
          - { label: "pasta", value: "pasta" }
          - { label: "pistacje", value: "pistacje" }
          - { label: "proteinowe", value: "proteinowe" }
          - { label: "przekąska", value: "przekąska" }
          - { label: "ryby", value: "ryby" }
          - { label: "Stefan", value: "Stefan" }
          - { label: "stefan", value: "stefan" }
          - { label: "szybkie", value: "szybkie" }
          - { label: "wegańskie", value: "wegańskie" }
          - { label: "łosoś", value: "łosoś" }
          - { label: "śliwki", value: "śliwki" }
        hint: "Wybierz z listy tagów (wpisz lub kliknij, aby zobaczyć wszystkie)."
      - { label: Kategorie, name: categories, widget: list, required: false }
      - { label: Podkategorie, name: subcategories, widget: list, required: false }
      - { label: Diety, name: diets, widget: list, required: false }
      - { label: Porcje, name: servings, widget: number, required: false, min: 1 }
      - { label: Czas przygotowania (min), name: prep_time, widget: number, required: false, min: 0 }
      - { label: Czy wymaga gotowania, name: cook, widget: boolean, required: false, default: false }
      - { label: Czas gotowania (minuty/godziny), name: cook_time, widget: string, required: false }
      - { label: Jednostka czasu gotowania, name: cook_increment, widget: string, required: false, hint: "minutes | hours" }
      - { label: Kalorie, name: calories, widget: number, required: false, min: 0 }
      - { label: Białko, name: protein, widget: number, required: false, min: 0 }
      - { label: Tłuszcz, name: fat, widget: number, required: false, min: 0 }
      - { label: Węglowodany, name: carbohydrate, widget: number, required: false, min: 0 }
      - { label: Link (YouTube itp.), name: link, widget: string, required: false }
      - label: Low FODMAP
        name: fodmap
        widget: object
        required: false
        collapsed: true
        fields:
          - { label: Status, name: status, widget: string, required: false }
          - { label: Notatki, name: notes, widget: text, required: false }
          - label: Zamienniki
            name: substitutions
            widget: list
            required: false
            field: { label: Zamiennik, name: substitution, widget: string }
          - { label: Porcja OK, name: serving_ok, widget: string, required: false }
      - label: Treść
        name: body
        widget: markdown
        hint: "Treść przepisu"
  - name: tagCollection
    label: Tagi
    files:
      - name: tags
        label: Lista tagów
        file: data/tags.json
        fields:
          - name: tags
            label: Wszystkie tagi
            widget: list
            fields:
              - { label: Nazwa, name: label, widget: string }
              - { label: Wartość, name: value, widget: string }
  - name: tagLibrary
    label: Biblioteka tagów (stara)
    folder: data/tags
    extension: yaml
    format: yaml
    create: true
    identifier_field: value
    slug: "{{value}}"
    fields:
      - { label: Nazwa do wyświetlenia, name: label, widget: string }
      - { label: Wartość (dokładny tag w front matter), name: value, widget: string }
