backend:
  name: github
  repo: GraniLuk/CookBook
  branch: main
  auth_type: pkce
  base_url: https://cookbook-cms-oauth.onrender.com/
  auth_endpoint: /auth
  app_id: Ov23liNlYyyS8AIONc4D
  scope: repo

site_url: https://graniluk.github.io/CookBook/
local_backend: true
publish_mode: simple
media_folder: static/images/uploaded
public_folder: /CookBook/images/uploaded
slug:
  encoding: ascii
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: recipes
    label: Przepisy
    label_singular: Przepis
    folder: content
    create: true
    slug: "{{slug}}"
    extension: md
    format: frontmatter
    nested:
      depth: 2
      summary: "{{title}}"
    fields:
      - { label: Tytuł, name: title, widget: string }
      - { label: Autor, name: author, widget: string, required: false }
      - { label: Szkic, name: draft, widget: boolean, required: false, default: false }
      - { label: Opis skrócony, name: tagline, widget: string, required: false }
      - { label: Obrazek przepisu (static/...), name: recipe_image, widget: string, required: false }
      - label: Tagi
        name: tags
        widget: select
        multiple: true
        required: false
        options:
          - { label: "batony", value: "batony" }
          - { label: "bez-pieczenia", value: "bez-pieczenia" }
          - { label: "brownie", value: "brownie" }
          - { label: "chrupiące", value: "chrupiące" }
          - { label: "goście", value: "goście" }
          - { label: "grill", value: "grill" }
          - { label: "impreza", value: "impreza" }
          - { label: "jesień", value: "jesień" }
          - { label: "kanapki", value: "kanapki" }
          - { label: "klasyczne", value: "klasyczne" }
          - { label: "kotlety", value: "kotlety" }
          - { label: "low carb", value: "low carb" }
          - { label: "lunchbox", value: "lunchbox" }
          - { label: "marokański", value: "marokański" }
          - { label: "meksykańskie", value: "meksykańskie" }
          - { label: "na-wynos", value: "na-wynos" }
          - { label: "pikantne", value: "pikantne" }
          - { label: "proteinowe", value: "proteinowe" }
          - { label: "przekąska", value: "przekąska" }
          - { label: "ryby", value: "ryby" }
          - { label: "Stefan", value: "Stefan" }
          - { label: "szybkie", value: "szybkie" }
          - { label: "wegańskie", value: "wegańskie" }
          - { label: "włoskie", value: "włoskie" }
        hint: "Wybierz z listy tagów (wpisz lub kliknij, aby zobaczyć wszystkie)."
      - { label: Kategorie, name: categories, widget: list, required: false }
      - { label: Podkategorie, name: subcategories, widget: list, required: false }
      - { label: Diety, name: diets, widget: list, required: false }
      - { label: Porcje, name: servings, widget: number, required: false, min: 1 }
      - { label: Czas przygotowania (min), name: prep_time, widget: number, required: false, min: 0 }
      - { label: Czy wymaga gotowania, name: cook, widget: boolean, required: false, default: false }
      - { label: Czas gotowania (minuty/godziny), name: cook_time, widget: string, required: false }
      - { label: Jednostka czasu gotowania, name: cook_increment, widget: string, required: false, hint: "minutes | hours" }
      - { label: Kalorie, name: calories, widget: number, required: false, min: 0 }
      - { label: Białko, name: protein, widget: number, required: false, min: 0 }
      - { label: Tłuszcz, name: fat, widget: number, required: false, min: 0 }
      - { label: Węglowodany, name: carbohydrate, widget: number, required: false, min: 0 }
      - { label: Link (YouTube itp.), name: link, widget: string, required: false }
      - label: Low FODMAP
        name: fodmap
        widget: object
        required: false
        collapsed: true
        fields:
          - { label: Status, name: status, widget: string, required: false }
          - { label: Notatki, name: notes, widget: text, required: false }
          - label: Zamienniki
            name: substitutions
            widget: list
            required: false
            field: { label: Zamiennik, name: substitution, widget: string }
          - { label: Porcja OK, name: serving_ok, widget: string, required: false }
      - label: Treść
        name: body
        widget: markdown
        hint: "Treść przepisu"

  - name: weekly_plans
    label: Plany Tygodniowe
    label_singular: Plan Tygodniowy
    folder: content/weekly-plans
    create: true
    slug: "{{year}}-W{{fields.week_number}}"
    extension: md
    format: frontmatter
    fields:
      - { label: Tytuł, name: title, widget: string, default: "Plan tygodnia" }
      - { label: Tydzień, name: week_number, widget: number, min: 1, max: 53, value_type: int }
      - { label: Rok, name: year, widget: number, default: 2025, value_type: int }
      - { label: Od dnia, name: start_date, widget: datetime, format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false, required: false }
      - { label: Notatki, name: notes, widget: text, required: false }
      - label: Poniedziałek
        name: monday
        widget: object
        collapsed: true
        fields:
          - { label: Śniadanie, name: breakfast, widget: relation, collection: recipes, search_fields: ["title"], value_field: "{{slug}}", display_fields: ["title"], required: false }
          - { label: Lunch, name: lunch, widget: relation, collection: recipes, search_fields: ["title"], value_field: "{{slug}}", display_fields: ["title"], required: false }
          - { label: Obiad, name: dinner, widget: relation, collection: recipes, search_fields: ["title"], value_field: "{{slug}}", display_fields: ["title"], required: false }
          - { label: Kolacja, name: supper, widget: relation, collection: recipes, search_fields: ["title"], value_field: "{{slug}}", display_fields: ["title"], required: false }
          - { label: Notatki, name: notes, widget: string, required: false }
      - label: Wtorek
        name: tuesday
        widget: object
        collapsed: true
        fields:
          - { label: Śniadanie, name: breakfast, widget: relation, collection: recipes, search_fields: ["title"], value_field: "{{slug}}", display_fields: ["title"], required: false }
          - { label: Lunch, name: lunch, widget: relation, collection: recipes, search_fields: ["title"], value_field: "{{slug}}", display_fields: ["title"], required: false }
          - { label: Obiad, name: dinner, widget: relation, collection: recipes, search_fields: ["title"], value_field: "{{slug}}", display_fields: ["title"], required: false }
          - { label: Kolacja, name: supper, widget: relation, collection: recipes, search_fields: ["title"], value_field: "{{slug}}", display_fields: ["title"], required: false }
          - { label: Notatki, name: notes, widget: string, required: false }
      - label: Środa
        name: wednesday
        widget: object
        collapsed: true
        fields:
          - { label: Śniadanie, name: breakfast, widget: relation, collection: recipes, search_fields: ["title"], value_field: "{{slug}}", display_fields: ["title"], required: false }
          - { label: Lunch, name: lunch, widget: relation, collection: recipes, search_fields: ["title"], value_field: "{{slug}}", display_fields: ["title"], required: false }
          - { label: Obiad, name: dinner, widget: relation, collection: recipes, search_fields: ["title"], value_field: "{{slug}}", display_fields: ["title"], required: false }
          - { label: Kolacja, name: supper, widget: relation, collection: recipes, search_fields: ["title"], value_field: "{{slug}}", display_fields: ["title"], required: false }
          - { label: Notatki, name: notes, widget: string, required: false }
      - label: Czwartek
        name: thursday
        widget: object
        collapsed: true
        fields:
          - { label: Śniadanie, name: breakfast, widget: relation, collection: recipes, search_fields: ["title"], value_field: "{{slug}}", display_fields: ["title"], required: false }
          - { label: Lunch, name: lunch, widget: relation, collection: recipes, search_fields: ["title"], value_field: "{{slug}}", display_fields: ["title"], required: false }
          - { label: Obiad, name: dinner, widget: relation, collection: recipes, search_fields: ["title"], value_field: "{{slug}}", display_fields: ["title"], required: false }
          - { label: Kolacja, name: supper, widget: relation, collection: recipes, search_fields: ["title"], value_field: "{{slug}}", display_fields: ["title"], required: false }
          - { label: Notatki, name: notes, widget: string, required: false }
      - label: Piątek
        name: friday
        widget: object
        collapsed: true
        fields:
          - { label: Śniadanie, name: breakfast, widget: relation, collection: recipes, search_fields: ["title"], value_field: "{{slug}}", display_fields: ["title"], required: false }
          - { label: Lunch, name: lunch, widget: relation, collection: recipes, search_fields: ["title"], value_field: "{{slug}}", display_fields: ["title"], required: false }
          - { label: Obiad, name: dinner, widget: relation, collection: recipes, search_fields: ["title"], value_field: "{{slug}}", display_fields: ["title"], required: false }
          - { label: Kolacja, name: supper, widget: relation, collection: recipes, search_fields: ["title"], value_field: "{{slug}}", display_fields: ["title"], required: false }
          - { label: Notatki, name: notes, widget: string, required: false }
      - label: Sobota
        name: saturday
        widget: object
        collapsed: true
        fields:
          - { label: Śniadanie, name: breakfast, widget: relation, collection: recipes, search_fields: ["title"], value_field: "{{slug}}", display_fields: ["title"], required: false }
          - { label: Lunch, name: lunch, widget: relation, collection: recipes, search_fields: ["title"], value_field: "{{slug}}", display_fields: ["title"], required: false }
          - { label: Obiad, name: dinner, widget: relation, collection: recipes, search_fields: ["title"], value_field: "{{slug}}", display_fields: ["title"], required: false }
          - { label: Kolacja, name: supper, widget: relation, collection: recipes, search_fields: ["title"], value_field: "{{slug}}", display_fields: ["title"], required: false }
          - { label: Notatki, name: notes, widget: string, required: false }
      - label: Niedziela
        name: sunday
        widget: object
        collapsed: true
        fields:
          - { label: Śniadanie, name: breakfast, widget: relation, collection: recipes, search_fields: ["title"], value_field: "{{slug}}", display_fields: ["title"], required: false }
          - { label: Lunch, name: lunch, widget: relation, collection: recipes, search_fields: ["title"], value_field: "{{slug}}", display_fields: ["title"], required: false }
          - { label: Obiad, name: dinner, widget: relation, collection: recipes, search_fields: ["title"], value_field: "{{slug}}", display_fields: ["title"], required: false }
          - { label: Kolacja, name: supper, widget: relation, collection: recipes, search_fields: ["title"], value_field: "{{slug}}", display_fields: ["title"], required: false }
          - { label: Notatki, name: notes, widget: string, required: false }